# build environment
FROM nginx:1.17
COPY build/ /usr/share/nginx/html

# production environment
#FROM nginx:stable-alpine
#COPY --from=build /usr/src/build /usr/share/nginx/html
#EXPOSE 80
#CMD ["nginx", "-g", "daemon off;"]
