apiVersion: apps/v1
kind: Deployment
metadata:
  name: ig-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ig-ui
  template:
    metadata:
      labels:
        app: ig-ui
    spec:
      containers:
        - name: ig-ui
#          image: iad.ocir.io/idjgmgwizrzb/ig-ui:latest
          image: ig-ui:latest
          workingDir: /usr/src
#          imagePullPolicy: "Always"
          imagePullPolicy: "Never"
          ports:
            - containerPort: 80
              name: http
#          env:
#            - name: DATABASE
#              valueFrom:
#                secretKeyRef:
#                  name: ig-ui-secrets
#                  key: DATABASE
          envFrom:
            - secretRef:
                name: ig-ui-secrets
#            - configMapRef:
#                name: ig-ui-config
      imagePullSecrets:
        - name: ocirsecret
