apiVersion: v1
kind: Service
metadata:
  name: ig-ui
  labels:
    app: ig-ui
spec:
  type: NodePort
#  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30002
  selector:
   app: ig-ui
