apiVersion: v1
kind: Secret
metadata:
  name: ig-ui-secrets
data:
  DATABASE: a3J3ZHNyY3BvcnRhbA==
  DATABASE_HOST: a3J3ZHNyYy1kYi1wb3N0Z3Jlc3FsLWhhLXBncG9vbC5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2Fs
  DATABASE_USER: cG9zdGdyZXM=
  DATABASE_PASSWORD: cGFzc3dvcmQ=
  DATABASE_PORT: NTQzMg==
  UI_PORT: ODAwMQ==
  SECRET: YXNkbHBscGxmd2Z3ZWZ3ZWt3c2VsZi4yMzQyLmRhd2FzcQ==

