apiVersion: v1
kind: Service
metadata:
  name: np-api
  labels:
    app: np-api
spec:
  type: NodePort
  ports:
    - port: 3001
      targetPort: 3001
      nodePort: 30001
  selector:
   app: np-api
