apiVersion: v1
kind: Service
metadata:
  name: fs-ui
  labels:
    app: fs-ui
spec:
  type: NodePort
#  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30003
  selector:
   app: fs-ui
